// app/lib/categoryIcons.ts
import {
  LucideIcon,
  Shirt,
  ShoppingBag,
  Home,
  Utensils,
  Sparkles,
  Scissors,
  Baby,
  Book,
  Dumbbell,
  Briefcase,
  Gem,
  Car,
  Bed,
  Feather,
  Cross,
  Cpu,
  Monitor,
  Sofa,
  Package,
  Crown,
  Truck,
  Gift,
  User,
  Users,
  Footprints,
  SprayCan,
  Camera,
  Heart,
  Box,
  Star,
} from "lucide-react";

// Categories with gradient
export const categoryIcons: Record<
  string,
  { icon: LucideIcon; gradient: string }
> = {
  "Women's Unstitched": { icon: Shirt, gradient: "from-pink-400 to-pink-600" },
  "Women's Stitched": { icon: ShoppingBag, gradient: "from-rose-400 to-rose-600" },
  "Home Essentials": { icon: Home, gradient: "from-teal-400 to-teal-600" },
  Kitchenware: { icon: Utensils, gradient: "from-orange-400 to-orange-600" },
  Cosmetics: { icon: Sparkles, gradient: "from-pink-500 to-fuchsia-600" },
  "Men's Unstitched": { icon: Shirt, gradient: "from-blue-400 to-blue-600" },
  "Men's Stitched": { icon: ShoppingBag, gradient: "from-indigo-400 to-indigo-600" },
  "Women's Shawls": { icon: Feather, gradient: "from-pink-300 to-pink-500" },
  "Men's Shawls": { icon: Feather, gradient: "from-blue-300 to-blue-500" },
  "Kids Clothing": { icon: Users, gradient: "from-yellow-400 to-orange-500" },
  "Women's Handbags": { icon: ShoppingBag, gradient: "from-pink-400 to-rose-500" },
  Jewellery: { icon: Gem, gradient: "from-amber-400 to-yellow-500" },
  "Auto & Bike Accessories": { icon: Car, gradient: "from-gray-500 to-gray-700" },
  "Home Linen": { icon: Bed, gradient: "from-teal-300 to-teal-500" },
  Bedding: { icon: Bed, gradient: "from-purple-400 to-purple-600" },
  "Women Undergarments": { icon: Scissors, gradient: "from-rose-400 to-rose-600" },
  "Islamic Accessories": { icon: Cross, gradient: "from-green-500 to-emerald-600" },
  "Electronic Accessories": { icon: Cpu, gradient: "from-sky-400 to-blue-600" },
  Electronics: { icon: Monitor, gradient: "from-indigo-400 to-indigo-600" },
  "Home Decor": { icon: Sofa, gradient: "from-fuchsia-400 to-purple-600" },
  Bags: { icon: Briefcase, gradient: "from-orange-400 to-red-500" },
  "Fashion Accessories": { icon: Crown, gradient: "from-amber-400 to-yellow-600" },
  Shoes: { icon: Footprints, gradient: "from-gray-600 to-black" },
  "Men's Undergarments": { icon: Scissors, gradient: "from-blue-400 to-indigo-600" },
  "Festive Collection": { icon: Gift, gradient: "from-red-400 to-pink-600" },
  Other: { icon: Package, gradient: "from-gray-400 to-gray-600" },
  "Kids Accessories": { icon: Users, gradient: "from-yellow-300 to-orange-400" },
  Perfumes: { icon: SprayCan, gradient: "from-pink-400 to-rose-600" },
  "Mother & Baby": { icon: Baby, gradient: "from-pink-300 to-yellow-400" },
  Brands: { icon: Crown, gradient: "from-indigo-400 to-indigo-600" },
  "Unisex Clothing": { icon: User, gradient: "from-purple-400 to-indigo-500" },
  "Books & Stationery": { icon: Book, gradient: "from-yellow-500 to-orange-600" },
  Fitness: { icon: Dumbbell, gradient: "from-green-500 to-emerald-700" },
  "Free Delivery": { icon: Truck, gradient: "from-blue-400 to-cyan-600" },
};

// Subcategories
export const subcategoryIcons: Record<string, LucideIcon> = {
  "Mobile Phones": Camera,
  Laptops: Cpu,
  "Men Clothing": Box,
  "Women Clothing": Heart,
  Toys: Star,
  Accessories: Box,
};
